<?php
$title = $this->getTitle();
$identify = $this->getIdentify();
$categoryIds = $this->getCatIds();
$categoryIds = explode(',', $categoryIds);
$_helper = $this->helper('catalog/output');
$productsOnRow = $this->getProductsOnRow();
if(!$productsOnRow) $productsOnRow = 3;
if ( !$this->getWidthThumbnail() ){
	$w_thumbnail = 135;
} else {
	$w_thumbnail = $this->getWidthThumbnail();
}
if( !$this->getHeightThumbnail() ){
	$h_thumbnail = 135;
 }
else {
	$h_thumbnail = $this->getHeightThumbnail();
}
?>

<div id="container">
<?php 	echo '<h2>'.$title.'</h2>'; ?>
  <ul class="tabs tabs<?php echo '-'.$identify;?>"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$cate_model = Mage::getModel('catalog/category');
		$cateName = $cate_model->load($cate_id)->getName();
		
		if($cateName) {
   ?>
			<li class="<?php if($k==0){ echo "active"; }?>" rel="tab<?php echo $cate_id.'-'.$identify;?>"><?php  echo $cateName; ?></li>
	<?php }  $k++; } ?>
    </ul>

	<div class="categorytabs tab_container"> 
		<?php foreach($categoryIds as $cate_id) { ?>
		 <div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?> mage-producttabs"> 
			<?php $_productCollection = $this->getProductCate($cate_id); ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $productsOnRow; ?>
		<?php $j=0; $time = $this->getPalayDelay(); ?>
		<?php $i=0; foreach ($_productCollection as $_product): ?>
		    <?php $t = $j*$time; $t .='ms'; $j++; ?>
			<?php if ($i++%$_columnCount==0): ?>
			<ul class="products-grid pdt-list zoomOut play">
			<?php endif ?>
				<li style="<?php echo "-webkit-animation-delay:$t;-moz-animation-delay:$t;-o-animation-delay:$t;animation-delay:$t" ?>;" class="item-animate item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
					<?php if($_product->getRatingSummary()): ?>
					<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					<?php endif; ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
					<div class="actions">
						<?php if($_product->isSaleable()): ?>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>
						</ul>
					</div>
				</li>
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			</ul>
			<?php endif ?>
			<?php endforeach ?>
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 

</div> <!-- #container -->

<script type="text/javascript">
jQuery(document).ready(function() {
	
	jQuery(".tab_content_<?php echo $identify; ?>").hide();
	jQuery(".tab_content_<?php echo $identify; ?>:first").show(); 

	jQuery("ul.tabs<?php echo '-'.$identify;?> li").click(function() {
		var activeTab = jQuery(this).attr("rel");

		jQuery("ul.tabs<?php echo '-'.$identify;?> li").removeClass("active");
		jQuery(this).addClass("active");
		resetAnimate("#"+activeTab); //require for Animate
		jQuery(".tab_content_<?php echo $identify; ?>").hide();
		jQuery("#"+activeTab).fadeIn(); // not show()
		setAnimate('#'+activeTab); //require for Animate
		
	});
});

	function resetAnimate(selector)
	{
		var parent = jQuery(selector).parent();
		jQuery('.pdt-list', parent).removeClass("play");
		jQuery('.pdt-list .item', parent).removeAttr('style');
	}

	function setAnimate(selector){
		var content = jQuery(selector);
		var parent = jQuery(selector).parent();
		$_items = jQuery('.item-animate', content);
		$_items.each(function(i){
			jQuery(this).attr("style", "-webkit-animation-delay:" + i * 300 + "ms;"
	                + "-moz-animation-delay:" + i * 300 + "ms;"
	                + "-o-animation-delay:" + i * 300 + "ms;"
	                + "animation-delay:" + i * 300 + "ms;");
			if (i == $_items.size() -1) {
				jQuery('.pdt-list', content).addClass("play");  // require for Animate
			}
		});
	}
</script> 