<?php if(Mage::getStoreConfig('testimonial/general_option/enable_sidebar') == 1):?>	
	<div class="testimonial">			
		<?php $latestTestimonial = $this->getTestimonialsLast()?>
		<?php if(count($latestTestimonial) > 0):?>
			<div class="testimonial-title">
				<h2><?php echo $this->__('Latest Testimonials')?></h2>
			</div>
			<div class="testimonial-content">
				<ul id="testimonialSidebar">			
					<?php foreach($latestTestimonial as $_item):?>							
						<li class="testimonial-list">									
							<div class="testimonial-sidebar-content">
								<div class="image_testimonial">
									 <div class="testimonial-content-avatar">
				                        <?php
				                            if($_item->getAvatarName() != ''){
				                                $avatarLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'magentothem/avatar/'.$_item->getAvatarName();
				                                ?><img src="<?php echo $avatarLink ?>" alt="test" height="105" width="105" /><?php
				                            }
				                        ?>
			                    	</div>
								</div>
								<div class="post-by">							
									<span class="testimonial-author"><?php echo $_item->getName(); ?></span>							
									<span class="testimonial-date"><?php echo date('F d, Y', Mage::getModel('core/date')->gmtTimestamp($_item->getCreatedTime())); ?></span>						
								</div>							
								<div class="std">							
									<a href="<?php echo $this->getUrl('testimonial')?>" title="">							    
									<?php									
										$_description = $_item->getTestimonial();									
										$short_desc = $this->getContentTestimonialSidebar($_description, 100);									
										echo $short_desc;							    ?>						   
									</a>					
								</div>						
											
							</div>				
						</li>							
					<?php endforeach;?>		
				</ul>
			</div>	
		<?php endif ?>	
	</div>
<?php endif ?>